package domain.models;

public enum Genre {
    // FICTION
    SCIENCE_FICTION, FANTACY, MISTERY, THRILLER, HORROR,
    ROMANCE, ADVENTURE, DYSTOPIAN,
    // NON-FICTION
    BIOGRAPHY, MEMOIR, SELF_HELP, HISTORY, TECHNOLOGY, SCIENCE,
    TRUE_CRIME, PSYCHOLOGY
}
